name: Fetch updated files in the repository.
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          changed_files = "test1.sh test2.sh test3.sh test4.sh test5.sh"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            if exists_in_list changed-files $file
              echo "File Exist"
            fi
          done
