name: Fetch updated files in the repository.
on:
  push:
    branches:
      - develop
env:
  FILE_NAMES: "test1.sh test2.sh test3.sh test4.sh"

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            for item in $FILE_NAMES
            do
              echo $item
              if [ "$file" == *"$item" ]; then
                echo "File is in the list"
                exit
              fi
            done
          done
      - name: Inline Python Script
        run:  |
          import os
          print(f"File name to check are {os.enviorn.get('FILE_NAMES')}")
          print("hello World")
          for item in range(0,5):
            print(item)
          print("Done")
        shell: python
